version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: cinebook_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  web:
    build: .
    container_name: cinebook_web
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=cinebook
    depends_on:
      - mongodb

volumes:
  mongo_data:
